apiVersion: v1
kind: Service
metadata:
  name: snake-service
  namespace: snake
  labels:
    app: snake
spec:
  type: NodePort
  selector:
    app: snake
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30009    
